# Generated by Django 5.2.7 on 2025-10-16 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('new_orders', models.BooleanField(default=True)),
                ('order_updates', models.BooleanField(default=True)),
                ('payment_updates', models.BooleanField(default=True)),
                ('stock_alerts', models.BooleanField(default=True)),
                ('new_users', models.BooleanField(default=True)),
                ('promotions', models.BooleanField(default=True)),
                ('system_updates', models.BooleanField(default=True)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('sound_volume', models.IntegerField(default=50)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificación',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_order', 'Nueva Orden'), ('order_status', 'Cambio de Estado de Orden'), ('payment_confirmed', 'Pago Confirmado'), ('payment_failed', 'Pago Fallido'), ('low_stock', 'Stock Bajo'), ('out_of_stock', 'Sin Stock'), ('new_user', 'Nuevo Usuario'), ('new_review', 'Nueva Reseña'), ('new_message', 'Nuevo Mensaje'), ('system', 'Sistema'), ('promotion', 'Promoción'), ('coupon_used', 'Cupón Usado')], default='system', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('icon', models.CharField(default='bell', help_text='Nombre del icono de Lucide React', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL a donde dirigir al hacer click', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración de la notificación', null=True)),
                ('is_broadcast', models.BooleanField(default=False, help_text='Si es True, se envía a todos los usuarios')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario receptor. Si es null, es una notificación global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'user'], name='notificatio_created_92565c_idx'), models.Index(fields=['read', 'user'], name='notificatio_read_7520e2_idx'), models.Index(fields=['type'], name='notificatio_type_8a8a78_idx')],
            },
        ),
    ]
