# Generated by Django 5.0 on 2025-10-07 20:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, upload_to='brands/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='Slug')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Descripción corta')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de comparación')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock')),
                ('low_stock_threshold', models.IntegerField(default=10, verbose_name='Umbral de stock bajo')),
                ('track_inventory', models.BooleanField(default=True, verbose_name='Rastrear inventario')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Largo (cm)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ancho (cm)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Alto (cm)')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta título')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('views', models.IntegerField(default=0, verbose_name='Vistas')),
                ('sales_count', models.IntegerField(default=0, verbose_name='Ventas totales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('attributes', models.JSONField(default=dict, verbose_name='Atributos')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Calificación')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='Compra verificada')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Aprobada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-created_at'],
            },
        ),
    ]
